### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Kotoki1337** [XutaxKamay/remote_manual_mapping-cheats#1]
1. What's the difference between using CUsercmd from CreateMove and using 
 "CUserCmdOverLoadedEqual"?
2. Isn't Detours detected by VAC?
3. What is "DeterminateSpeedKey" and its references in SDK?
4. What does [this](https://github.com/XutaxKamay/Cheats-Stuffs/blob/master/DLL_CSGO/new_InputStuffs.cpp#L11-L14) do?

**Comment by XutaxKamay** [comment]
1) You don't need anymore to do the checksum for writeusercmddeltabuffer, the cusercmd structure contained a equal overloaded function, it seemed better to me to hook it there
2) I didn't care of vac back then, yet, I never really looked about how vac is working since they never cared about me, cuz I never got banned for detours
3) It was used for having proper frametime for my optimizer, basically it just computes proper frametime for mouse movement etc
4) It updates prediction  when framerate is lower than tickrate (because prediction update only occurs when a new frame is done, but since you can have 2 ticks processed in one frame, that's where the issue with prediction came), the offsets that I took are just the respective arguments that the engine did call previously

**Comment by Kotoki1337** [comment]
thanks for u reply!
